on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  py-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: actions/setup-python@v6.2.0
    - uses: astral-sh/ruff-action@v4.1.0
      with:
        args: check
        version-file: "uv.lock"

  py-typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: actions/setup-python@v6.2.0
      with:
        python-version: "3.12"
    - uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv sync --all-groups
    - name: Run mypy
      run: uv run mypy src backends datalayer integration tests

  py-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: actions/setup-python@v6.2.0
      with:
        python-version: "3.12"
    - uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv sync --all-groups
    - name: Run pytest
      run: uv run pytest
